from pathlib import Path
import argparse, logging, json
import numpy as np
import pandas as pd

from src.config import Config
from src.database import get_engine, check_connection, reset_schemas
from src.data_loader import load_csvs, upload_raw
from src.exporter import export_table
from src.logging_config import configure_logging
from src.validation import validate_outputs, assert_close
from src.visualization import make_figures
from src.summary_builder import build_summary

def pct(x): return float(x)*100

def build_models(d):
    orders=d['olist_orders_dataset.csv'].copy(); customers=d['olist_customers_dataset.csv']; items=d['olist_order_items_dataset.csv'].copy(); payments=d['olist_order_payments_dataset.csv'].copy(); reviews=d['olist_order_reviews_dataset.csv'].copy(); products=d['olist_products_dataset.csv']; trans=d['product_category_name_translation.csv']; sellers=d['olist_sellers_dataset.csv']
    item_agg=items.groupby('order_id',as_index=False).agg(gross_product_value=('price','sum'),total_freight_value=('freight_value','sum'),item_count=('order_item_id','nunique'),seller_count=('seller_id','nunique'),item_row_count=('order_id','size')); item_agg['gross_order_value']=item_agg.gross_product_value+item_agg.total_freight_value
    pay_agg=payments.groupby('order_id',as_index=False).agg(total_payment_value=('payment_value','sum'),payment_count=('payment_sequential','nunique'),payment_row_count=('order_id','size'))
    reviews['review_answer_timestamp']=pd.to_datetime(reviews.review_answer_timestamp,errors='coerce'); reviews['review_creation_date']=pd.to_datetime(reviews.review_creation_date,errors='coerce'); reviews=reviews.sort_values(['order_id','review_answer_timestamp','review_creation_date','review_id'],na_position='first'); review_counts=reviews.groupby('order_id',as_index=False).agg(review_record_count=('review_id','size')); resolved=reviews.drop_duplicates('order_id',keep='last')[['order_id','review_id','review_score','review_creation_date','review_answer_timestamp']]
    fact=orders.merge(customers[['customer_id','customer_unique_id','customer_state']],on='customer_id',how='left',validate='many_to_one').merge(item_agg,on='order_id',how='left').merge(pay_agg,on='order_id',how='left').merge(resolved,on='order_id',how='left').merge(review_counts,on='order_id',how='left')
    for col in ['gross_product_value','total_freight_value','gross_order_value','total_payment_value','item_count','seller_count','item_row_count','payment_count','payment_row_count','review_record_count']: fact[col]=fact[col].fillna(0)
    fact['eligible']=fact.order_status.eq('delivered') & fact.order_delivered_customer_date.notna() & fact.order_estimated_delivery_date.notna()
    fact['delivered_date']=fact.order_delivered_customer_date.dt.date; fact['estimated_date']=fact.order_estimated_delivery_date.dt.date
    fact['delay_days']=(fact.delivered_date.astype('string').replace('NaT',np.nan).pipe(pd.to_datetime,errors='coerce')-fact.estimated_date.astype('string').replace('NaT',np.nan).pipe(pd.to_datetime,errors='coerce')).dt.days
    fact['delivery_class']=np.select([fact.eligible & (fact.delay_days<0),fact.eligible & (fact.delay_days==0),fact.eligible & (fact.delay_days>0)],['Early','On Time','Late'],default='Not Eligible')
    fact['approval_days']=(fact.order_approved_at-fact.order_purchase_timestamp).dt.total_seconds()/86400; fact['processing_days']=(fact.order_delivered_carrier_date-fact.order_approved_at).dt.total_seconds()/86400; fact['shipping_days']=(fact.order_delivered_customer_date-fact.order_delivered_carrier_date).dt.total_seconds()/86400; fact['total_delivery_days']=(fact.order_delivered_customer_date-fact.order_purchase_timestamp).dt.total_seconds()/86400
    fact['low_review']=fact.review_score.le(2)
    item_fact=items.merge(products[['product_id','product_category_name']],on='product_id',how='left').merge(trans,on='product_category_name',how='left').merge(fact[['order_id','customer_state','order_status','eligible','delivery_class','delay_days','gross_order_value','review_score']],on='order_id',how='left'); item_fact['category']=item_fact.product_category_name_english.fillna(item_fact.product_category_name).fillna('Unknown')
    seller_fact=items.merge(fact[['order_id','eligible','delivery_class','delay_days','gross_order_value','review_score']],on='order_id',how='left').groupby(['order_id','seller_id'],as_index=False).agg(seller_shipping_limit_date=('shipping_limit_date','min'),item_count=('order_item_id','nunique'),seller_item_value=('price','sum'),seller_freight_value=('freight_value','sum'),eligible=('eligible','first'),delivery_class=('delivery_class','first'),delay_days=('delay_days','first'),gross_order_value=('gross_order_value','first'),review_score=('review_score','first')); carrier=fact[['order_id','order_delivered_carrier_date']]; seller_fact=seller_fact.merge(carrier,on='order_id'); seller_fact['dispatch_sla_breach']=seller_fact.order_delivered_carrier_date>seller_fact.seller_shipping_limit_date
    return {'orders':orders,'items':items,'payments':payments,'reviews':reviews,'products':products,'sellers':sellers,'translation':trans,'item_summary':item_agg,'payment_summary':pay_agg,'review_resolved':resolved.merge(review_counts,on='order_id',how='left'),'fact_order':fact,'fact_item':item_fact,'fact_seller':seller_fact}

def make_analyses(m, cfg, out):
    f=m['fact_order']; eligible=f[f.eligible].copy(); late=eligible[eligible.delivery_class.eq('Late')]; ontime=eligible[eligible.delivery_class.isin(['Early','On Time'])]
    dur=[]
    for col,label in [('approval_days','Approval'),('processing_days','Processing'),('shipping_days','Shipping'),('total_delivery_days','Total delivery')]:
        valid=eligible[col].dropna(); valid=valid[valid>=0]; dur.append({'stage':label,'valid_order_count':len(valid),'median_days':valid.median(),'p75_days':valid.quantile(.75),'p90_days':valid.quantile(.90),'invalid_duration_count':int((eligible[col].dropna()<0).sum())})
    metrics={'total_orders':len(f),'delivered_orders':int(f.order_status.eq('delivered').sum()),'eligible_delivered_orders':len(eligible),'early_orders':int((eligible.delivery_class=='Early').sum()),'on_time_orders':int((eligible.delivery_class=='On Time').sum()),'late_orders':len(late),'late_delivery_rate':pct(len(late)/len(eligible)) if len(eligible) else 0,'average_delay_days':late.delay_days.mean(),'median_delay_days':late.delay_days.median(),'p90_delay_days':late.delay_days.quantile(.9),'eligible_gross_order_value':eligible.gross_order_value.sum(),'at_risk_order_value':late.gross_order_value.sum(),'at_risk_order_value_share':pct(late.gross_order_value.sum()/eligible.gross_order_value.sum()) if eligible.gross_order_value.sum() else 0,'on_time_average_review_score':ontime.review_score.mean(),'late_average_review_score':late.review_score.mean(),'review_score_gap':ontime.review_score.mean()-late.review_score.mean(),'cancellation_and_unavailable_rate':pct(f.order_status.isin(['canceled','unavailable']).mean()),'delivery_timestamp_coverage':pct(f.order_delivered_customer_date.notna().mean()),'review_coverage_rate':pct(eligible.review_score.notna().mean())}
    export_table(pd.DataFrame({'metric':list(metrics),'value':list(metrics.values())}),out,'executive_kpis.csv'); export_table(pd.DataFrame(dur),out,'process_stage_metrics.csv')
    months=eligible.assign(month=eligible.order_purchase_timestamp.dt.to_period('M').astype(str)).groupby('month',as_index=False).agg(eligible_orders=('order_id','nunique'),late_orders=('delivery_class',lambda x:(x=='Late').sum()),late_delivery_rate=('delivery_class',lambda x:pct((x=='Late').mean())),median_total_delivery_days=('total_delivery_days','median'),at_risk_order_value=('gross_order_value',lambda x:x[eligible.loc[x.index,'delivery_class'].eq('Late')].sum()),average_review_score=('review_score','mean'),review_coverage=('review_score',lambda x:pct(x.notna().mean()))); export_table(months,out,'monthly_delivery_performance.csv')
    buckets=np.select([eligible.delay_days<0,eligible.delay_days==0,eligible.delay_days.between(1,3),eligible.delay_days.between(4,7),eligible.delay_days.between(8,14),eligible.delay_days>=15],['Early','On Time','1-3 Days Late','4-7 Days Late','8-14 Days Late','15+ Days Late'],default='Unknown'); sev=eligible.assign(severity_bucket=buckets).groupby('severity_bucket',as_index=False).agg(order_count=('order_id','nunique'),reviewed_order_count=('review_score',lambda x:x.notna().sum()),average_review_score=('review_score','mean'),low_review_rate=('low_review','mean')); sev['low_review_rate']=sev.low_review_rate*100; export_table(sev,out,'delay_review_impact.csv')
    var=pd.DataFrame([{'population':'Eligible delivered orders','order_count':len(eligible),'gross_order_value':eligible.gross_order_value.sum()},{'population':'Late eligible delivered orders','order_count':len(late),'gross_order_value':late.gross_order_value.sum()}]); var['share_of_eligible_value']=var.gross_order_value/eligible.gross_order_value.sum()*100; export_table(var,out,'value_at_risk_summary.csv')
    sf=m['fact_seller']; ss=sf[sf.eligible].groupby('seller_id',as_index=False).agg(eligible_orders=('order_id','nunique'),late_orders=('delivery_class',lambda x:(x=='Late').sum()),late_delivery_rate=('delivery_class',lambda x:pct((x=='Late').mean())),dispatch_sla_breach_rate=('dispatch_sla_breach',lambda x:pct(x.mean())),median_processing_days=('order_id','size'),at_risk_order_value=('gross_order_value',lambda x:x[sf.loc[x.index,'delivery_class'].eq('Late')].sum())); ss['platform_late_delivery_rate']=metrics['late_delivery_rate']; ss=ss[ss.eligible_orders>=cfg.min_seller_orders].copy(); ss['priority_group']=np.select([(ss.late_delivery_rate>metrics['late_delivery_rate'])&(ss.dispatch_sla_breach_rate>ss.dispatch_sla_breach_rate.median())&(ss.at_risk_order_value>ss.at_risk_order_value.median()),(ss.late_delivery_rate>metrics['late_delivery_rate'])|(ss.dispatch_sla_breach_rate>ss.dispatch_sla_breach_rate.median()),ss.late_delivery_rate<=metrics['late_delivery_rate']],['Investigate Now','Process Watch','Stable'],default='Monitor'); export_table(ss.sort_values(['priority_group','at_risk_order_value'],ascending=[True,False]),out,'seller_priority.csv')
    it=m['fact_item']; cat=it[it.eligible].groupby('category',as_index=False).agg(eligible_orders=('order_id','nunique'),item_count=('order_id','size'),late_delivery_rate=('delivery_class',lambda x:pct((x=='Late').mean())),at_risk_item_value=('price',lambda x:x[it.loc[x.index,'delivery_class'].eq('Late')].sum()),average_review_score=('review_score','mean')); cat=cat[cat.eligible_orders>=cfg.min_category_orders]; export_table(cat.sort_values('at_risk_item_value',ascending=False),out,'category_priority.csv')
    reg=eligible.groupby('customer_state',as_index=False).agg(eligible_orders=('order_id','nunique'),late_delivery_rate=('delivery_class',lambda x:pct((x=='Late').mean())),median_shipping_days=('shipping_days','median'),at_risk_order_value=('gross_order_value',lambda x:x[eligible.loc[x.index,'delivery_class'].eq('Late')].sum()),average_review_score=('review_score','mean')); reg=reg[reg.eligible_orders>=cfg.min_region_orders]; export_table(reg.sort_values('at_risk_order_value',ascending=False),out,'regional_performance.csv')
    recon=pd.DataFrame([{'metric':'eligible_gross_order_value','value':eligible.gross_order_value.sum()},{'metric':'total_payment_value','value':eligible.total_payment_value.sum()},{'metric':'value_reconciliation_gap','value':eligible.total_payment_value.sum()-eligible.gross_order_value.sum()}]); export_table(recon,out,'value_reconciliation_summary.csv')
    pri=pd.DataFrame({'priority_area':['Delivery rate','Value exposure','Customer experience','Process investigation'],'evidence':[f"{metrics['late_delivery_rate']:.1f}% late across {len(eligible):,} eligible orders",f"BRL {metrics['at_risk_order_value']:,.2f} at-risk gross order value",f"{metrics['review_score_gap']:.2f} point review gap",'Compare processing, shipping, and dispatch SLA patterns']}); export_table(pri,out,'management_priority_summary.csv')
    return metrics

def data_quality(m,out,row_counts):
    f=m['fact_order']; it=m['items']; pay=m['payments']; rev=m['reviews']; rows=[]
    def add(check,status,value,detail=''): rows.append({'check_name':check,'severity':status,'value':value,'detail':detail})
    add('source_row_count_total','INFO',sum(row_counts.values())); add('order_fact_unique_order_id','CRITICAL' if f.order_id.duplicated().any() else 'PASS',int(f.order_id.nunique()),'COUNT(*) must equal COUNT(DISTINCT order_id)'); add('order_item_composite_duplicates','CRITICAL' if it.duplicated(['order_id','order_item_id']).any() else 'PASS',int(it.duplicated(['order_id','order_item_id']).sum())); add('payment_composite_duplicates','CRITICAL' if pay.duplicated(['order_id','payment_sequential']).any() else 'PASS',int(pay.duplicated(['order_id','payment_sequential']).sum())); add('review_multiplicity_orders','WARNING',int((rev.groupby('order_id').size()>1).sum())); add('negative_item_values','WARNING',int(((it.price<0)|(it.freight_value<0)).sum())); add('delivered_missing_delivery_date','WARNING',int(((f.order_status=='delivered')&f.order_delivered_customer_date.isna()).sum())); add('invalid_processing_duration','WARNING',int((m['fact_order'].processing_days.dropna()<0).sum())); add('multi_item_order_rate','INFO',pct((f.item_count>1).mean())); add('multi_seller_order_rate','INFO',pct((f.seller_count>1).mean())); add('multi_payment_order_rate','INFO',pct((f.payment_count>1).mean())); add('review_score_invalid','CRITICAL',int((~rev.review_score.between(1,5)).sum())); export_table(pd.DataFrame(rows),out,'data_quality_summary.csv')

def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--stage',choices=['load','quality','models','analysis','validate','visualize','summary']); args=parser.parse_args(); cfg=Config.from_env(); log=configure_logging(cfg.output_dir); cfg.output_dir.joinpath('tables').mkdir(parents=True,exist_ok=True); cfg.output_dir.joinpath('figures').mkdir(parents=True,exist_ok=True)
    if not cfg.raw_dir.exists(): raise RuntimeError(f'Raw data directory missing: {cfg.raw_dir}')
    engine=get_engine(cfg); check_connection(engine); data,row_counts=load_csvs(cfg.raw_dir); reset_schemas(engine); upload_raw(data,engine); models=build_models(data)
    for name,df in [('int_order_item_summary',models['item_summary']),('int_order_payment_summary',models['payment_summary']),('int_order_review_resolved',models['review_resolved']),('fact_order_delivery',models['fact_order']),('fact_order_seller_delivery',models['fact_seller']),('fact_order_item_delivery',models['fact_item'])]: df.to_sql(name,engine,schema='analytics',if_exists='replace',index=False,chunksize=5000,method='multi')
    data_quality(models,cfg.output_dir,row_counts); metrics=make_analyses(models,cfg,cfg.output_dir); validate_outputs(cfg.output_dir); make_figures(cfg.output_dir/'tables',cfg.output_dir/'figures'); build_summary(cfg.output_dir)
    # Independent-equivalent reconciliation checks from exported outputs.
    k=pd.read_csv(cfg.output_dir/'tables'/'executive_kpis.csv').set_index('metric')['value']; monthly=pd.read_csv(cfg.output_dir/'tables'/'monthly_delivery_performance.csv'); assert_close(monthly.eligible_orders.sum(),k['eligible_delivered_orders'],'monthly eligible orders'); assert_close(k.early_orders+k.on_time_orders+k.late_orders,k.eligible_delivered_orders,'delivery classes'); assert_close(k.at_risk_order_value,k.eligible_gross_order_value*k.at_risk_order_value_share/100,'at-risk share'); log.info('Pipeline completed successfully: %s eligible orders, %.2f%% late, BRL %.2f at-risk value',int(k.eligible_delivered_orders),float(k.late_delivery_rate),float(k.at_risk_order_value))

if __name__=='__main__': main()
