from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def _style():
    sns.set_theme(style='whitegrid', context='notebook')
    plt.rcParams.update({'figure.dpi':120,'axes.titleweight':'bold','axes.labelsize':10})

def make_figures(tables: Path, figures: Path):
    figures.mkdir(parents=True, exist_ok=True); _style()
    m = pd.read_csv(tables/'monthly_delivery_performance.csv'); fig, ax = plt.subplots(2,1,figsize=(11,7),sharex=True); ax[0].plot(m.month,m.late_delivery_rate,marker='o',color='#b23a48'); ax[0].set_ylabel('Late delivery rate (%)'); ax[0].set_title('Monthly delivery performance'); ax[1].bar(m.month,m.eligible_orders,color='#3c6e71'); ax[1].set_ylabel('Eligible orders'); ax[1].tick_params(axis='x',rotation=45); fig.tight_layout(); fig.savefig(figures/'01_monthly_delivery_performance.png',bbox_inches='tight'); plt.close(fig)
    p = pd.read_csv(tables/'process_stage_metrics.csv'); fig, ax = plt.subplots(figsize=(10,5)); x=range(len(p)); ax.bar([i-.18 for i in x],p.median_days,width=.36,label='Median'); ax.bar([i+.18 for i in x],p.p90_days,width=.36,label='P90'); ax.set_xticks(list(x),p.stage,rotation=20); ax.set_ylabel('Days'); ax.set_title('Process stage duration'); ax.legend(); fig.tight_layout(); fig.savefig(figures/'02_process_stage_duration.png',bbox_inches='tight'); plt.close(fig)
    d = pd.read_csv(tables/'delay_review_impact.csv'); fig, ax = plt.subplots(figsize=(10,5)); sns.barplot(data=d,x='severity_bucket',y='average_review_score',ax=ax,color='#284b63'); ax.set_ylim(0,5); ax.set_ylabel('Average review score'); ax.set_title('Review score by delay severity'); ax.tick_params(axis='x',rotation=20); fig.tight_layout(); fig.savefig(figures/'03_review_score_by_delay_severity.png',bbox_inches='tight'); plt.close(fig)
    s = pd.read_csv(tables/'seller_priority.csv'); fig, ax = plt.subplots(figsize=(10,6)); q=s.copy(); q['bubble']=q.at_risk_order_value.clip(lower=1); sc=ax.scatter(q.eligible_orders,q.late_delivery_rate,s=q.bubble/q.bubble.max()*700+25,c=q.dispatch_sla_breach_rate,cmap='RdYlGn_r',alpha=.75,edgecolor='white'); ref=q.platform_late_delivery_rate.iloc[0] if len(q) else 0; ax.axhline(ref,color='black',ls='--',label='Platform late rate'); ax.set_xlabel('Eligible order volume'); ax.set_ylabel('Late delivery rate (%)'); ax.set_title('Seller priority matrix'); ax.legend(); fig.colorbar(sc,ax=ax,label='Dispatch SLA breach rate (%)'); fig.tight_layout(); fig.savefig(figures/'04_seller_priority_matrix.png',bbox_inches='tight'); plt.close(fig)
    c = pd.read_csv(tables/'category_priority.csv'); fig, ax = plt.subplots(figsize=(10,6)); sc=ax.scatter(c.eligible_orders,c.late_delivery_rate,s=c.at_risk_item_value.clip(lower=1)/max(c.at_risk_item_value.max(),1)*700+25,c=c.average_review_score,cmap='RdYlGn',alpha=.8,edgecolor='white'); ax.set_xlabel('Eligible category order volume'); ax.set_ylabel('Late delivery rate (%)'); ax.set_title('Category priority matrix'); fig.colorbar(sc,ax=ax,label='Average review score'); fig.tight_layout(); fig.savefig(figures/'05_category_priority_matrix.png',bbox_inches='tight'); plt.close(fig)
    r = pd.read_csv(tables/'regional_performance.csv'); fig, ax = plt.subplots(figsize=(10,6)); sns.scatterplot(data=r,x='eligible_orders',y='late_delivery_rate',size='median_shipping_days',hue='median_shipping_days',sizes=(50,400),palette='viridis',ax=ax); ax.set_xlabel('Eligible order volume'); ax.set_ylabel('Late delivery rate (%)'); ax.set_title('Regional delivery performance'); fig.tight_layout(); fig.savefig(figures/'06_regional_delivery_performance.png',bbox_inches='tight'); plt.close(fig)
